// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZgzuZyPEsRt1XAb-A_04WMWUyFxStc0',
    appId: '1:213752844763:web:675b68fc915da404df97fe',
    messagingSenderId: '213752844763',
    projectId: 'zensefit',
    authDomain: 'zensefit.firebaseapp.com',
    storageBucket: 'zensefit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxkYClaPvvffuSXK3kGD8LRbUQokEndI',
    appId: '1:213752844763:android:0abd86c77ae37811df97fe',
    messagingSenderId: '213752844763',
    projectId: 'zensefit',
    storageBucket: 'zensefit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHSbtp5HnaLFxLwAgAmhCWF0X5-ujZWU',
    appId: '1:213752844763:ios:2a9955515cc00b39df97fe',
    messagingSenderId: '213752844763',
    projectId: 'zensefit',
    storageBucket: 'zensefit.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGZgzuZyPEsRt1XAb-A_04WMWUyFxStc0',
    appId: '1:213752844763:web:6618cdb9730f55bddf97fe',
    messagingSenderId: '213752844763',
    projectId: 'zensefit',
    authDomain: 'zensefit.firebaseapp.com',
    storageBucket: 'zensefit.appspot.com',
  );
}
